#
# Makefile for the '2048' game (TMGDL 1.5)
#
#   make            build the game (the compiler is selected in MACROS)
#   make install    copy the game to $(BINDIR)
#   make clean      remove the compiled files
#
# Build and install the library first (SRC\BUILD). TMT Pascal is used
# unless 'make' is given -DUSE_BPC or -DUSE_FPC, which BUILD.BAT does with
# 'BUILD BPC' or 'BUILD FPC'.
#
!include "../../src/macros"

INCLUDE=globals.inc \
	engine.inc \
	game.inc \
	backgd.inc

all:	2048.exe

2048.exe: 2048.pas $(INCLUDE)
	@$(PC) $(LFLAGS) 2048.pas
	@if exist 2048.o   $(RM) 2048.o
	@if exist 2048.fpd $(RM) 2048.fpd
	@if exist 2048.sym $(RM) 2048.sym

install: 2048.exe
	@if not exist $(BINDIR)\NUL $(MD) $(BINDIR)
	$(CP) 2048.exe $(BINDIR)
	$(CP) 2048.hlp $(BINDIR)

clean:
	@if exist 2048.exe $(RM) 2048.exe
	@if exist 2048.o   $(RM) 2048.o
	@if exist 2048.fpd $(RM) 2048.fpd
	@if exist 2048.sym $(RM) 2048.sym
