#
# Makefile for the 'TETRIS' game (TMGDL 1.5)
#
#   make            build the game (the compiler is selected in MACROS)
#   make install    copy the game to $(BINDIR)
#   make clean      remove the compiled files
#
# Build and install the library first (SRC\BUILD). TMT Pascal is used
# unless 'make' is given -DUSE_BPC or -DUSE_FPC, which BUILD.BAT does with
# 'BUILD BPC' or 'BUILD FPC'.
#
!include "../../src/macros"

INCLUDE=globals.inc \
	engine.inc \
	game.inc \
	backgd.inc

all:	tetris.exe

tetris.exe: tetris.pas $(INCLUDE)
	@$(PC) $(LFLAGS) tetris.pas
	@if exist tetris.o   $(RM) tetris.o
	@if exist tetris.fpd $(RM) tetris.fpd
	@if exist tetris.sym $(RM) tetris.sym

install: tetris.exe
	@if not exist $(BINDIR)\NUL $(MD) $(BINDIR)
	$(CP) tetris.exe $(BINDIR)
	$(CP) tetris.hlp $(BINDIR)

clean:
	@if exist tetris.exe $(RM) tetris.exe
	@if exist tetris.o   $(RM) tetris.o
	@if exist tetris.fpd $(RM) tetris.fpd
	@if exist tetris.sym $(RM) tetris.sym
