#
# Makefile for the 'TIC-TAC-TOE' game (TMGDL 1.5)
#
#   make            build the game (the compiler is selected in MACROS)
#   make install    copy the game to $(BINDIR)
#   make clean      remove the compiled files
#
# Build and install the library first (SRC\BUILD). TMT Pascal is used
# unless 'make' is given -DUSE_BPC or -DUSE_FPC, which BUILD.BAT does with
# 'BUILD BPC' or 'BUILD FPC'.
#
!include "../../src/macros"

INCLUDE=globals.inc \
	engine.inc \
	game.inc \
	backgd.inc

all:	t3.exe

t3.exe: t3.pas $(INCLUDE)
	@$(PC) $(LFLAGS) t3.pas
	@if exist t3.o   $(RM) t3.o
	@if exist t3.fpd $(RM) t3.fpd
	@if exist t3.sym $(RM) t3.sym

install: t3.exe
	@if not exist $(BINDIR)\NUL $(MD) $(BINDIR)
	$(CP) t3.exe $(BINDIR)
	$(CP) t3.hlp $(BINDIR)

clean:
	@if exist t3.exe $(RM) t3.exe
	@if exist t3.o   $(RM) t3.o
	@if exist t3.fpd $(RM) t3.fpd
	@if exist t3.sym $(RM) t3.sym
