#
# Makefile for the 'GAME OF LIFE' game (TMGDL 1.5)
#
#   make            build the game (the compiler is selected in MACROS)
#   make install    copy the game to $(BINDIR)
#   make clean      remove the compiled files
#
#   make patterns.exe   build PATTERNS, which turns PATTERNS.TXT into
#                       PATTERNS.INC
#
# Build and install the library first (SRC\BUILD). TMT Pascal is used
# unless 'make' is given -DUSE_BPC or -DUSE_FPC, which BUILD.BAT does with
# 'BUILD BPC' or 'BUILD FPC'.
#
!include "../../src/macros"

INCLUDE=globals.inc \
	engine.inc \
	game.inc \
	backgd.inc \
	patterns.inc

all:	gol.exe

gol.exe: gol.pas $(INCLUDE)
	@$(PC) $(LFLAGS) gol.pas
	@if exist gol.o   $(RM) gol.o
	@if exist gol.fpd $(RM) gol.fpd
	@if exist gol.sym $(RM) gol.sym

patterns.exe: patterns.pas
	@$(PC) $(LFLAGS) patterns.pas
	@if exist patterns.o   $(RM) patterns.o
	@if exist patterns.fpd $(RM) patterns.fpd
	@if exist patterns.sym $(RM) patterns.sym

install: gol.exe
	@if not exist $(BINDIR)\NUL $(MD) $(BINDIR)
	$(CP) gol.exe $(BINDIR)
	$(CP) gol.hlp $(BINDIR)

clean:
	@if exist gol.exe $(RM) gol.exe
	@if exist gol.o   $(RM) gol.o
	@if exist gol.fpd $(RM) gol.fpd
	@if exist gol.sym $(RM) gol.sym
	@if exist patterns.exe $(RM) patterns.exe
	@if exist patterns.o   $(RM) patterns.o
	@if exist patterns.fpd $(RM) patterns.fpd
	@if exist patterns.sym $(RM) patterns.sym
